name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  nix:
    name: NixOS / Qt 6.6.2
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix --experimental-features 'nix-command flakes' build -L .
      - name: Flake check
        run: nix --experimental-features 'nix-command flakes' flake check .
      - name: Format
        run: nix --experimental-features 'nix-command flakes' fmt && git diff --exit-code
