name: WebAssembly

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  pages: write

env:
  emsdk_cache_dir: "emsdk-cache"

jobs:
  ubuntu-qt6-wasm:
    name: Qt 6.6.3 / Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup emsdk cache
        uses: actions/cache@v4
        with:
          key: emsdk-cache
          path: ${{ env.emsdk_cache_dir }}

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.37
          actions-cache-folder: ${{ env.emsdk_cache_dir }}

      - name: Setup CMake
        uses: ./.github/actions/cmake
        with:
          qt_version: 6.6.3
          qt_arch: wasm_singlethread
          use_qt6: ON
          modules: qtwebsockets

      - name: Build
        run: cmake --build '${{github.workspace}}/build' --parallel "$(nproc)"
        shell: bash

      - name: Consolidate WebAssembly artifacts
        run: |
          mkdir gh-sources
          cp '${{github.workspace}}'/build/shvspy/*.{js,wasm,html} gh-sources/
          mv gh-sources/shvspy.html gh-sources/index.html
          cp '${{github.workspace}}'/distro/shvspy.AppDir/shvspy.svg gh-sources/qtlogo.svg
        shell: bash

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'gh-sources/'

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/deploy-pages@v4
